version: "3.9"
services:
  mysql-service:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysql-container
    networks:
      - user-network
    environment:
      MYSQL_ROOT_PASSWORD: pass@123
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: pass@123
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  mongodb-service:
    image: mongo:latest
    container_name: mongo-container
    networks:
      - user-network
    ports:
      - "27017:27017"

  user-authentication-service:
    container_name: user-authentication-service
    build: AuthApplication/
    networks:
      - user-network
    ports:
      - "8086:8086"
    depends_on:
      - mysql-service
    restart: always

  user-service:
    container_name: user-service
    build: productApplication/
    networks:
      - user-network
    ports:
      - "8081:8081"
    depends_on:
      - mongodb-service
    restart: always

  api-gateway:
    container_name: gateway-container
    build: ApiGateway/
    networks:
      - user-network
    ports:
      - "65500:65500"

networks:
  user-network:
    driver: bridge

